---

- import_tasks: dependencies.yml
- import_tasks: setup.yml
- import_tasks: mariadb.yml
- import_tasks: wordpress.yml
- import_tasks: nginx.yml
- import_tasks: phpmyadmin.yml

- name: Run docker-compose
  command: docker compose up -d
  args:
    chdir: /home/rcabezas/inception/
