---

- name: Add the user 'rcabezas'
  ansible.builtin.user:
    name: rcabezas
    shell: /bin/bash
    groups: sudo
    append: yes

- name: Create database folder
  file:
    path: /home/rcabezas/data/db
    state: directory

- name: Create wordpress folder
  file:
    path: /home/rcabezas/data/wordpress
    state: directory

- name: Copy inception folder
  copy:
    src: ../files/inception
    dest: /home/rcabezas
